export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_HUMANS_PENDING = 'REQUEST_HUMANS_PENDING';
export const REQUEST_HUMANS_SUCCESS = 'REQUEST_HUMANS_SUCCESS';
export const REQUEST_HUMANS_FAILED = 'REQUEST_HUMANS_FAILED';